# If you are using intellij ultimate, you can test the simulator with this file

GET localhost:8090

###

GET localhost:8090/transAmericanAirline/flight-offers
Accept: application/json
Content-Type: application/json

{
  "date": "2020-06-20"
}

###


GET localhost:8090/adiosAirline/flight-offers
Accept: application/json
Content-Type: application/json

{
  "date": "2020-06-20"
}

###